apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-memory-app-prometheus
  labels:
    app: dotnet-memory-app-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-memory-app-prometheus
  template:
    metadata:
      labels:
        app: dotnet-memory-app-prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: dotnet-memory-app
        image: awaybreaktoday/dotnet-memory-app:v2.0.1-amd64  # Updated with Prometheus
        ports:
        - containerPort: 5000
          name: metrics
          protocol: TCP
        resources:
          limits:
            memory: "1024Mi"
            cpu: "200m"
          requests:
            memory: "512Mi"
            cpu: "100m"
        env:
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: "true"
        - name: DOTNET_GCHeapHardLimitPercent
          value: "70"
        - name: DOTNET_GCServer
          value: "true"
        - name: DOTNET_GCConserveMemory
          value: "9"
        - name: DOTNET_GCRetainVM
          value: "0"
        # Health check
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-memory-app-service
  labels:
    app: dotnet-memory-app-prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: dotnet-memory-app-prometheus
  ports:
  - name: metrics
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP

---
# ServiceMonitor for Prometheus Operator (if using)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dotnet-memory-app-monitor
  labels:
    app: dotnet-memory-app-prometheus
spec:
  selector:
    matchLabels:
      app: dotnet-memory-app-prometheus
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
